version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      USEPOLLING: "true"
    command: sh -c "npm run dev"
    